package com.ejemplo.DAOs.Implementaciones.Oracle;

import java.sql.*;
import java.util.ArrayList;
import java.util.List;
import javax.sql.DataSource;

import com.ejemplo.DAOs.Interfaces.CursoDAO;
import com.ejemplo.Modelos.Curso;
import com.ejemplo.Modelos.Programa;
import com.ejemplo.Utils.Erros.SqlErrorDetailer;

public class CursoDAOOracle implements CursoDAO {

    private final DataSource dataSource;
    private static CursoDAOOracle cursoDAOOracle;

    private CursoDAOOracle(DataSource dataSource) {
        this.dataSource = dataSource;
    }

    public static CursoDAOOracle crearCursoDAOOracle(DataSource dataSource){
        if(cursoDAOOracle == null){
            synchronized (CursoDAOOracle.class){
                if(cursoDAOOracle == null){
                    cursoDAOOracle = new CursoDAOOracle(dataSource);
                }
            }
        }
        return cursoDAOOracle;
    }

    @Override
    public Curso guardar(Curso entidad) {
        // DDL: CURSO(id GENERATED BY DEFAULT AS IDENTITY, nombre NOT NULL, programa_id NOT NULL, activo NUMBER(1) DEFAULT 1 NOT NULL)
        final String insertSql = "INSERT INTO CURSO (nombre, programa_id, activo) VALUES (?, ?, ?)";

        try (Connection con = dataSource.getConnection();
            PreparedStatement ps = con.prepareStatement(insertSql, new String[] { "ID" })) {

            ps.setString(1, entidad.getNombre());

            // OBLIGATORIO: programa_id es NOT NULL en el DDL
            if (entidad.getPrograma() == null) {
                throw new SQLException("programa_id es obligatorio (NOT NULL)");
            }
            ps.setLong(2, (long)entidad.getPrograma().getID());

            // NUMBER(1) para booleano
            ps.setInt(3, entidad.isActivo() ? 1 : 0);

            int updated = ps.executeUpdate();
            if (updated != 1) throw new SQLException("No se insertó CURSO (updated=" + updated + ")");

            try (ResultSet keys = ps.getGeneratedKeys()) {
                if (keys.next()) {
                    // tu modelo usa setId(int); ajusta si es long
                    entidad.setId((int) keys.getLong(1));
                }
            }
            return entidad;

        } catch (SQLException e) {
            throw SqlErrorDetailer.wrap(e, "INSERT CURSO (ORACLE)", insertSql,
                    entidad.getNombre(),
                    (entidad.getPrograma() == null ? null : entidad.getPrograma().getID()),
                    entidad.isActivo());
        }
    }

    @Override
    public List<Curso> listar() {
        final String sql = "SELECT id, nombre, programa_id, activo FROM CURSO ORDER BY nombre";
        List<Curso> lista = new ArrayList<>();
        try (Connection con = dataSource.getConnection();
             PreparedStatement ps = con.prepareStatement(sql);
             ResultSet rs = ps.executeQuery()) {

            while (rs.next()) lista.add(mapRow(rs));
            return lista;

        } catch (SQLException e) {
            throw new RuntimeException("Error al listar CURSOS (ORACLE)", e);
        }
    }

    @Override
    public void actualizar(Curso entidad) {
        final String sql = "UPDATE CURSO SET nombre = ?, programa_id = ?, activo = ? WHERE id = ?";
        try (Connection con = dataSource.getConnection();
             PreparedStatement ps = con.prepareStatement(sql)) {

            ps.setString(1, entidad.getNombre());
            if (entidad.getPrograma() != null) {
                ps.setLong(2, (long) entidad.getPrograma().getID());
            } else {
                ps.setNull(2, Types.NUMERIC);
            }
            ps.setInt(3, entidad.isActivo() ? 1 : 0);
            ps.setLong(4, entidad.getId());
            ps.executeUpdate();

        } catch (SQLException e) {
            throw SqlErrorDetailer.wrap(e, "UPDATE CURSO (ORACLE)", sql,
                    entidad.getNombre(),
                    (entidad.getPrograma() == null ? null : entidad.getPrograma().getID()),
                    entidad.isActivo(),
                    entidad.getId());
        }
    }

    @Override
    public void eliminar(Long id) {
        final String sql = "DELETE FROM CURSO WHERE id = ?";
        try (Connection con = dataSource.getConnection();
             PreparedStatement ps = con.prepareStatement(sql)) {

            ps.setLong(1, id);
            ps.executeUpdate();

        } catch (SQLException e) {
            throw SqlErrorDetailer.wrap(e, "DELETE CURSO (ORACLE)", sql, id);
        }
    }

    private Curso mapRow(ResultSet rs) throws SQLException {
        Curso c = new Curso();
        c.setId((int) rs.getLong("id"));
        c.setNombre(rs.getString("nombre"));

        // activo NUMBER(1) -> booleano
        int activoNum = rs.getInt("activo");
        c.setActivo(!rs.wasNull() && activoNum == 1);

        long pid = rs.getLong("programa_id");
        if (!rs.wasNull()) {
            Programa p = new Programa();
            p.setID(pid);
            c.setPrograma(p);
        }
        return c;
    }
}
